name: Compile Sketch

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  # Manual trigger
  workflow_dispatch:

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install Platformio
        run: |
          python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

      - name: Build Gaggiuino
        run: |
          ~/.platformio/penv/bin/platformio run
